truffle-compile:
	truffle compile
truffle-migrate:
	truffle migrate
truffle-make-migrate:
	truffle create migration deploy_sample_contract
truffle-make-constract:
	truffle create contract SimpleContract